apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deployment-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:   # This should be aligned with 'metadata'
      containers:
        - name: frontend
          image: gcr.io/giit-interns/frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
