name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Authenticate to GCP
      run: echo "${{ secrets.GCP_SA_KEY }}" | gcloud auth activate-service-account --key-file=-

    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_CLUSTER_ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy backend to GKE
      run: kubectl apply -f k8s/backend-deployment.yml

    - name: Deploy frontend to GKE
      run: kubectl apply -f k8s/frontend-deployment.yml

    - name: Deploy MySQL to GKE
      run: kubectl apply -f k8s/mysql-deployment.yml
