name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  buildandpush:
    name: Build Frontend Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Frontend
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: Authenticate GCR
      run: |
        gcloud info
        gcloud auth configure-docker "gcr.io/$GCP_PROJECT_ID" --quiet

    - name: Build Image
      run: |
        docker build -t "gcr.io/$GCP_PROJECT_ID/frontend:latest" .


    - name: Push Image
      run: |
        docker tag "gcr.io/$GCP_PROJECT_ID"/frontend:latest "gcr.io/$GCP_PROJECT_ID"/frontend:latest
        docker push "gcr.io/$GCP_PROJECT_ID"/frontend:latest
