name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  buildandpush:
    name: Build Frontend Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Frontend
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: Authenticate GCR
      run: |
        gcloud auth configure-docker "gcr.io/${{ secrets.GCP_PROJECT_ID }}/" 

    - name: Build Image
      working-directory: ./frontend
      run: |
        docker buildx build --platform linux/amd64 -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend:latest -f Dockerfile .

    - name: Push Frontend Image
      run:  |
        #docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend:latest
        docker tag gcr.io/giit-411012/frontend:latest gcr.io/giit-411012/frontend:v1
        docker push gcr.io/giit-411012/frontend:v1 
