name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  buildandpush:
    name: Build Frontend Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Frontend
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: Authenticate GCR
      run: |
        gcloud auth configure-docker "us-central1-docker.pkg.dev" 

    - name: Build Image
      working-directory: ./frontend
      run: |
        docker buildx build --platform linux/amd64 -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/frontend:latest -f Dockerfile .

    - name: Push Frontend Image
      run:  |
        #docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/frontend:latest
        docker tag us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/frontend:latest us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/frontend:v1
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/frontend:v1 
